### ISSUE TITLE
JSON: Server Frontend Communication

### ISSUE THREAD

**Issue by fstiehle** [fstiehle/de.htwg.wt.nmm#5]
Mehrere pucks sollen einzeln gesendet werden konnen.
Unterscheidung: set/pick, move

Hier statisch: 
 ```
function requestCommand(command, pucks) {
        var data = { command: command, pucks: {puck1: pucks[0], puck2: pucks[1]} };
        ...
    }
```

**Comment by fstiehle** [comment]
Bitte in master mergen wenn fertig

**Comment by fstiehle** [comment]
TODO: Append status message to JSON file

**Comment by fstiehle** [comment]
TODO:
- Game Reset Request
- Player name change request

**Comment by FunkeMT** [comment]
- Status in Json:
see: https://github.com/FunkeMT/de.htwg.se.nmm/commit/2345febc06dac18342216a28e9a159eaab997567
```
{
  "status": {
    "modus": "SET",
    "man": "WHITE",
    "message": "Player 1: It's now time to set.",
    "pucksLeft": 8
  }
}
```

- Player name change request:
see: 5253bff and 9f7b079
-- edit name with double click on player name
-- accept with focus-out and enter
-- abort with ESC
@fstiehle Please verify if JS is at correct location

- Open TODO:
-- Game Reset Request

**Comment by fstiehle** [comment]
Requirement for Angular2:

- Route to receive boardDefinition.json

**Comment by FunkeMT** [comment]
@fstiehle 
> Route to receive boardDefinition.json

There is still a route to this file, because its an usually asset `http://localhost:9000/assets/board/boardDefinition.json`

*Attention: assets actually are not secured!*

**Comment by FunkeMT** [comment]
@fstiehle 

Please use for **blocking** tasks an own issue and tag it as *blocking*.

**Comment by FunkeMT** [comment]
refer to #17 and #18
