### ISSUE TITLE
numPucks

### ISSUE THREAD

**Issue by fstiehle** [fstiehle/de.htwg.wt.nmm#8]
Each Player starts with 9 pucks.
Should be set to 12 when testing is done.

 private static final int NUM_PUCKS = 9;

**Comment by FunkeMT** [comment]
https://en.wikipedia.org/wiki/Nine_Men's_Morris

>  Each player has **nine** pieces, or "men", usually coloured black and white.

**Comment by FunkeMT** [comment]
Lie down again.
